style: dark
header_pages:
  - index.md
  - about.md
  - hof.md
  - blog.md
  - medium.md
  - linkedin.md
  - github.md
  - twitter.md
  - hackerone.md
  - bugcrowd.md
  
  

footer: 'follow me on <a href="https://twitter.com/ahmetumitbayram">twitter</a>'

plugins:
  - jekyll-seo-tag
