title: 'Exploit Artist'
description: "Exploit Artist"
baseurl: "/"
url: "https://ahmetumitbayram.github.io"

header_pages:
  - index.md
  - about.md
  - blog.md
  - exploit.md
  - contact.md

collections:
  posts:
    output: true

  
style: hacker

footer: 'exploit artist - copyLeft 2024</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
