title: 'ahmetumitbayram.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
url: "https://ahmetumitbayram.github.io"

header_pages:
  - index.md
  - whoami.md
  - about.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://twitter.com/">ahmetumitbayram</a>'
